version: '3.7'

services:
  neo4j:
    image: neo4j:4.4
    container_name: "snomed2neo_neo"
    volumes:
      - ./.neo4j/neo4mimic_experiment_exp/data:/data 
      - ./.neo4j/neo4mimic_experiment_exp/logs:/logs 
      - ./.neo4j/neo4mimic_experiment_exp/import:/var/lib/neo4j/import 
      - ./.neo4j/neo4mimic_experiment_exp/plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/passw0rd
      - NEO4JLABS_PLUGINS=["graph-data-science", "bloom"]
      # - apoc.import.file.enabled=true
      # - NEO4J_dbms_memory_pagecache_size=4G
      - NEO4j_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=8G
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:7474/", "||", "exit 1"] 
      interval: 10s
      timeout: 2s
      retries: 10
    # networks:
    #   - neo_net
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "snomed2neo_py"
    volumes:
      - ./code:/app
      - ./vocabularies:/vocabularies
      - ./mimic-preprocessed:/mimic-preprocessed
    stdin_open: true # docker run -i
    ports:
      - 8888:8888
    tty: true
    depends_on:
      - neo4j
